# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_Post',
            new_name='BlogPost',
        ),
    ]
